package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultStore;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.zzab;
import dalvik.annotation.Signature;
import java.util.concurrent.TimeUnit;

/* compiled from: dalvik_source_com.waze.apk */
public class zzrt<R extends Result> extends PendingResult<R> {
    private final Status cp;

    public zzrt(Status $r1) throws  {
        zzab.zzb((Object) $r1, (Object) "Status must not be null");
        zzab.zzb(!$r1.isSuccess(), (Object) "Status must not be success");
        this.cp = $r1;
    }

    @NonNull
    public R await() throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    public R await(@Signature({"(J", "Ljava/util/concurrent/TimeUnit;", ")TR;"}) long j, @NonNull @Signature({"(J", "Ljava/util/concurrent/TimeUnit;", ")TR;"}) TimeUnit timeUnit) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void cancel() throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    Status getStatus() throws  {
        return this.cp;
    }

    public boolean isCanceled() throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void setResultCallback(@NonNull @Signature({"(", "Lcom/google/android/gms/common/api/ResultCallback", "<-TR;>;)V"}) ResultCallback<? super R> resultCallback) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void setResultCallback(@NonNull @Signature({"(", "Lcom/google/android/gms/common/api/ResultCallback", "<-TR;>;J", "Ljava/util/concurrent/TimeUnit;", ")V"}) ResultCallback<? super R> resultCallback, @Signature({"(", "Lcom/google/android/gms/common/api/ResultCallback", "<-TR;>;J", "Ljava/util/concurrent/TimeUnit;", ")V"}) long j, @NonNull @Signature({"(", "Lcom/google/android/gms/common/api/ResultCallback", "<-TR;>;J", "Ljava/util/concurrent/TimeUnit;", ")V"}) TimeUnit timeUnit) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void store(@NonNull ResultStore resultStore, int i) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull @Signature({"<S::", "Lcom/google/android/gms/common/api/Result;", ">(", "Lcom/google/android/gms/common/api/ResultTransform", "<-TR;+TS;>;)", "Lcom/google/android/gms/common/api/TransformedResult", "<TS;>;"}) ResultTransform<? super R, ? extends S> resultTransform) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void zza(@NonNull zza com_google_android_gms_common_api_PendingResult_zza) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Nullable
    public Integer zzasb() throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void zzhp(int i) throws  {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
